#!/bin/bash

echo "=== IRC Server Testing Guide ==="
echo ""
echo "1. Start your IRC server:"
echo "   ./irc_serv 6667 mypassword"
echo ""
echo "2. In another terminal, test with telnet:"
echo "   telnet localhost 6667"
echo ""
echo "3. Test commands manually:"
echo "   PASS mypassword"
echo "   NICK testuser"
echo "   USER testuser 0 * :Test User"
echo ""
echo "4. Test TCP chunks by typing slowly:"
echo "   Type: 'PRIVMSG #test :Hello' (don't press Enter)"
echo "   Wait 2 seconds, then type: ' World!' and press Enter"
echo ""
echo "5. Test with netcat (sends all at once):"
echo "   echo -e 'PASS mypassword\\r\\nNICK testuser\\r\\n' | nc localhost 6667"
echo ""
echo "6. Test with HexChat IRC client:"
echo "   - Server: localhost"
echo "   - Port: 6667" 
echo "   - Password: mypassword"
echo ""
echo "=== Expected Behavior ==="
echo "- Server should wait for complete messages ending with \\r\\n"
echo "- Partial messages should be buffered until \\r\\n is received"
echo "- Multiple messages in one packet should be processed separately"
echo "- Each client should have its own buffer"
echo ""
echo "=== What to observe in server output ==="
echo "- 'New client connected: IP (fd: X)' when client connects"
echo "- 'Response:' lines showing server replies"
echo "- No errors about incomplete commands"
echo "- Commands only execute when complete (with \\r\\n)"
